//
// AuthErrorResponseError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthErrorResponseError: Sendable, Codable, Hashable {

    public var message: String?
    public var reason: String?

    public init(message: String? = nil, reason: String? = nil) {
        self.message = message
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

