//
// CalendarEventDeleteRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields for deleting a calendar event. */
public struct CalendarEventDeleteRequestBody: Sendable, Codable, Hashable {

    /** ID of the calendar-event to be deleted */
    public var id: Int

    public init(id: Int) {
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
    }
}


extension CalendarEventDeleteRequestBody: Identifiable {}
