//
// CalendarEventUpdateRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields for updating a calendar event. Only supplied fields will be updated. At least one field other than &#39;id&#39; must be provided. */
public struct CalendarEventUpdateRequestBody: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case invited = "INVITED"
        case tentative = "TENTATIVE"
        case confirmed = "CONFIRMED"
        case rejected = "REJECTED"
        case cancelled = "CANCELLED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Title of the event */
    public var title: String?
    /** Detailed description of the event */
    public var description: String?
    /** Start date and time as Unix timestamp */
    public var startTimestamp: Int64?
    /** End date and time as Unix timestamp */
    public var endTimestamp: Int64?
    /** Status of the event */
    public var status: Status? = .tentative
    /** Creator of the event */
    public var organiser: String?
    /** Person attending the event */
    public var attendee: String?
    /** Event location */
    public var location: String?
    /** ID of the calendar-event to be updated */
    public var id: Int

    public init(title: String? = nil, description: String? = nil, startTimestamp: Int64? = nil, endTimestamp: Int64? = nil, status: Status? = .tentative, organiser: String? = nil, attendee: String? = nil, location: String? = nil, id: Int) {
        self.title = title
        self.description = description
        self.startTimestamp = startTimestamp
        self.endTimestamp = endTimestamp
        self.status = status
        self.organiser = organiser
        self.attendee = attendee
        self.location = location
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case startTimestamp = "start_timestamp"
        case endTimestamp = "end_timestamp"
        case status
        case organiser
        case attendee
        case location
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(endTimestamp, forKey: .endTimestamp)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(organiser, forKey: .organiser)
        try container.encodeIfPresent(attendee, forKey: .attendee)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encode(id, forKey: .id)
    }
}


extension CalendarEventUpdateRequestBody: Identifiable {}

extension CalendarEventUpdateRequestBody: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
