//
// CalendarAppointmentCreateRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields for creating a calendar event of type &#39;Appointment&#39; */
public struct CalendarAppointmentCreateRequestBody: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case invited = "INVITED"
        case tentative = "TENTATIVE"
        case confirmed = "CONFIRMED"
        case rejected = "REJECTED"
        case cancelled = "CANCELLED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum Context: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case referral = "referral"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Title of the event */
    public var title: String
    /** Detailed description of the event */
    public var description: String?
    /** Start date and time as Unix timestamp */
    public var startTimestamp: Int64
    /** End date and time as Unix timestamp */
    public var endTimestamp: Int64
    /** Status of the event */
    public var status: Status = .tentative
    /** Creator of the event */
    public var organiser: String?
    /** Person attending the event */
    public var attendee: String?
    /** Event location */
    public var location: String?
    /** The context the appointment belongs to e.g. a referral */
    public var context: Context
    /** The id of the specific context record that this appointment relates to e.g. the referral id */
    public var contextId: Int

    public init(title: String, description: String? = nil, startTimestamp: Int64, endTimestamp: Int64, status: Status = .tentative, organiser: String? = nil, attendee: String? = nil, location: String? = nil, context: Context, contextId: Int) {
        self.title = title
        self.description = description
        self.startTimestamp = startTimestamp
        self.endTimestamp = endTimestamp
        self.status = status
        self.organiser = organiser
        self.attendee = attendee
        self.location = location
        self.context = context
        self.contextId = contextId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case startTimestamp = "start_timestamp"
        case endTimestamp = "end_timestamp"
        case status
        case organiser
        case attendee
        case location
        case context
        case contextId = "context_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(startTimestamp, forKey: .startTimestamp)
        try container.encode(endTimestamp, forKey: .endTimestamp)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(organiser, forKey: .organiser)
        try container.encodeIfPresent(attendee, forKey: .attendee)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encode(context, forKey: .context)
        try container.encode(contextId, forKey: .contextId)
    }
}


extension CalendarAppointmentCreateRequestBody: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if context == .unknownDefaultOpenApi { return true }
        return false
    }
}
