//
// CreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateResponse: Sendable, Codable, Hashable {

    /** Indicates success */
    public var success: Int?
    /** ID of the newly created record */
    public var lastInsertId: Int?

    public init(success: Int? = nil, lastInsertId: Int? = nil) {
        self.success = success
        self.lastInsertId = lastInsertId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case lastInsertId = "last_insert_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(lastInsertId, forKey: .lastInsertId)
    }
}

