//
// GetAppointmentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAppointmentsResponse: Sendable, Codable, Hashable {

    public var success: Int?
    public var appointments: [CalendarEvent]?

    public init(success: Int? = nil, appointments: [CalendarEvent]? = nil) {
        self.success = success
        self.appointments = appointments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case appointments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(appointments, forKey: .appointments)
    }
}

