//
// GetEventsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetEventsResponse: Sendable, Codable, Hashable {

    public var success: Int?
    public var events: [CalendarEvent]?

    public init(success: Int? = nil, events: [CalendarEvent]? = nil) {
        self.success = success
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

