//
// ReferralSingleResponseReferral.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReferralSingleResponseReferral: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case referred = "Referred"
        case inProgress = "In Progress"
        case accepted = "Accepted"
        case rejected = "Rejected"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int?
    public var createdTimestamp: Int64?
    public var serviceId: Int?
    public var type: String?
    public var status: Status?
    public var memo: String?

    public init(id: Int? = nil, createdTimestamp: Int64? = nil, serviceId: Int? = nil, type: String? = nil, status: Status? = nil, memo: String? = nil) {
        self.id = id
        self.createdTimestamp = createdTimestamp
        self.serviceId = serviceId
        self.type = type
        self.status = status
        self.memo = memo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdTimestamp = "created_timestamp"
        case serviceId = "service_id"
        case type
        case status
        case memo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(serviceId, forKey: .serviceId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(memo, forKey: .memo)
    }
}


extension ReferralSingleResponseReferral: Identifiable {}

extension ReferralSingleResponseReferral: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
