//
// ReferralCommonRequestBodyFieldsReferreeAvailability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Availability of the referree. If not provided, defaults to empty AM/PM arrays. */
public struct ReferralCommonRequestBodyFieldsReferreeAvailability: Sendable, Codable, Hashable {

    /** Morning availability slots */
    public var AM: [String]?
    /** Afternoon availability slots */
    public var PM: [String]?

    public init(AM: [String]? = nil, PM: [String]? = nil) {
        self.AM = AM
        self.PM = PM
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case AM
        case PM
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(AM, forKey: .AM)
        try container.encodeIfPresent(PM, forKey: .PM)
    }
}

