//
// ReferralListResponseReferralsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReferralListResponseReferralsInner: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case referred = "Referred"
        case inProgress = "In Progress"
        case accepted = "Accepted"
        case rejected = "Rejected"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int?
    public var createdTimestamp: Int64?
    public var serviceId: Int?
    public var serviceName: String?
    public var serviceDescription: String?
    public var serviceContactNumber: String?
    public var serviceEmail: String?
    public var serviceUrl: String?
    public var type: String?
    public var status: Status?

    public init(id: Int? = nil, createdTimestamp: Int64? = nil, serviceId: Int? = nil, serviceName: String? = nil, serviceDescription: String? = nil, serviceContactNumber: String? = nil, serviceEmail: String? = nil, serviceUrl: String? = nil, type: String? = nil, status: Status? = nil) {
        self.id = id
        self.createdTimestamp = createdTimestamp
        self.serviceId = serviceId
        self.serviceName = serviceName
        self.serviceDescription = serviceDescription
        self.serviceContactNumber = serviceContactNumber
        self.serviceEmail = serviceEmail
        self.serviceUrl = serviceUrl
        self.type = type
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdTimestamp = "created_timestamp"
        case serviceId = "service_id"
        case serviceName = "service_name"
        case serviceDescription = "service_description"
        case serviceContactNumber = "service_contact_number"
        case serviceEmail = "service_email"
        case serviceUrl = "service_url"
        case type
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(serviceId, forKey: .serviceId)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(serviceDescription, forKey: .serviceDescription)
        try container.encodeIfPresent(serviceContactNumber, forKey: .serviceContactNumber)
        try container.encodeIfPresent(serviceEmail, forKey: .serviceEmail)
        try container.encodeIfPresent(serviceUrl, forKey: .serviceUrl)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(status, forKey: .status)
    }
}


extension ReferralListResponseReferralsInner: Identifiable {}

extension ReferralListResponseReferralsInner: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
