//
// ReferralSingleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing a single referral (requires query parameter &#39;id&#39;) */
public struct ReferralSingleResponse: Sendable, Codable, Hashable {

    public var success: Int?
    public var referral: ReferralSingleResponseReferral?

    public init(success: Int? = nil, referral: ReferralSingleResponseReferral? = nil) {
        self.success = success
        self.referral = referral
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case referral
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(referral, forKey: .referral)
    }
}

