//
// ReferralCommonRequestBodyFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Common fields shared across all referral types */
public struct ReferralCommonRequestBodyFields: Sendable, Codable, Hashable {

    /** ID of the service being referred to */
    public var serviceId: Int?
    /** Background information about the referree */
    public var referreeBackground: String?
    /** Requirements of the referree */
    public var referreeRequirements: String?
    public var referreeAvailability: ReferralCommonRequestBodyFieldsReferreeAvailability?
    /** Name of the person making the referral */
    public var referrerName: String?
    /** Name of the service */
    public var serviceName: String?
    /** Description of the service */
    public var serviceDescription: String?
    /** URL of the service */
    public var serviceUrl: String?
    /** Email address of the service */
    public var serviceEmail: String?
    /** Contact number for the service */
    public var contactNumber: String?
    /** Internal memo or notes */
    public var memo: String?
    /** Start time as a Unix timestamp */
    public var startTime: Int64?

    public init(serviceId: Int? = nil, referreeBackground: String? = nil, referreeRequirements: String? = nil, referreeAvailability: ReferralCommonRequestBodyFieldsReferreeAvailability? = nil, referrerName: String? = nil, serviceName: String? = nil, serviceDescription: String? = nil, serviceUrl: String? = nil, serviceEmail: String? = nil, contactNumber: String? = nil, memo: String? = nil, startTime: Int64? = nil) {
        self.serviceId = serviceId
        self.referreeBackground = referreeBackground
        self.referreeRequirements = referreeRequirements
        self.referreeAvailability = referreeAvailability
        self.referrerName = referrerName
        self.serviceName = serviceName
        self.serviceDescription = serviceDescription
        self.serviceUrl = serviceUrl
        self.serviceEmail = serviceEmail
        self.contactNumber = contactNumber
        self.memo = memo
        self.startTime = startTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceId = "service_id"
        case referreeBackground = "referree_background"
        case referreeRequirements = "referree_requirements"
        case referreeAvailability = "referree_availability"
        case referrerName = "referrer_name"
        case serviceName = "service_name"
        case serviceDescription = "service_description"
        case serviceUrl = "service_url"
        case serviceEmail = "service_email"
        case contactNumber = "contact_number"
        case memo
        case startTime = "start_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(serviceId, forKey: .serviceId)
        try container.encodeIfPresent(referreeBackground, forKey: .referreeBackground)
        try container.encodeIfPresent(referreeRequirements, forKey: .referreeRequirements)
        try container.encodeIfPresent(referreeAvailability, forKey: .referreeAvailability)
        try container.encodeIfPresent(referrerName, forKey: .referrerName)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(serviceDescription, forKey: .serviceDescription)
        try container.encodeIfPresent(serviceUrl, forKey: .serviceUrl)
        try container.encodeIfPresent(serviceEmail, forKey: .serviceEmail)
        try container.encodeIfPresent(contactNumber, forKey: .contactNumber)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(startTime, forKey: .startTime)
    }
}

