//
// ReferralStatusUpdateRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields for updating the status of a referral (e.g. from &#39;Referred&#39; to &#39;Accepted&#39;) */
public struct ReferralStatusUpdateRequestBody: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case referred = "Referred"
        case inProgress = "In Progress"
        case accepted = "Accepted"
        case rejected = "Rejected"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** ID of the referral to be updated */
    public var id: Int
    /** Status the referral is to be updated to */
    public var status: Status

    public init(id: Int, status: Status) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}


extension ReferralStatusUpdateRequestBody: Identifiable {}

extension ReferralStatusUpdateRequestBody: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
