//
// ReferralListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing a list of referrals */
public struct ReferralListResponse: Sendable, Codable, Hashable {

    public var success: Int?
    public var referrals: [ReferralListResponseReferralsInner]?

    public init(success: Int? = nil, referrals: [ReferralListResponseReferralsInner]? = nil) {
        self.success = success
        self.referrals = referrals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case referrals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(referrals, forKey: .referrals)
    }
}

