//
// SecureMessageSendRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to send a secure message */
public struct SecureMessageSendRequest: Sendable, Codable, Hashable {

    /** Content of the message */
    public var messageContent: String
    /** ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context. */
    public var conversationId: String
    /** Recipient user ID */
    public var messageTo: String

    public init(messageContent: String, conversationId: String, messageTo: String) {
        self.messageContent = messageContent
        self.conversationId = conversationId
        self.messageTo = messageTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageContent = "message_content"
        case conversationId = "conversation_id"
        case messageTo = "message_to"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messageContent, forKey: .messageContent)
        try container.encode(conversationId, forKey: .conversationId)
        try container.encode(messageTo, forKey: .messageTo)
    }
}

