//
// SecureMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single message within a conversation */
public struct SecureMessage: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case sent = "sent"
        case received = "received"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Message ID */
    public var id: String?
    /** Conversation identifier */
    public var conversationId: String?
    /** Recipient of the message (present on sent messages) */
    public var messageTo: String?
    /** Sender of the message (present on received messages) */
    public var messageFrom: String?
    /** Timestamp when message was sent */
    public var timeSent: String?
    /** Timestamp when message was received */
    public var timeReceived: String?
    /** Content of the message */
    public var messageContent: String?
    /** Message status */
    public var status: Status?

    public init(id: String? = nil, conversationId: String? = nil, messageTo: String? = nil, messageFrom: String? = nil, timeSent: String? = nil, timeReceived: String? = nil, messageContent: String? = nil, status: Status? = nil) {
        self.id = id
        self.conversationId = conversationId
        self.messageTo = messageTo
        self.messageFrom = messageFrom
        self.timeSent = timeSent
        self.timeReceived = timeReceived
        self.messageContent = messageContent
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case conversationId = "conversation_id"
        case messageTo = "message_to"
        case messageFrom = "message_from"
        case timeSent = "time_sent"
        case timeReceived = "time_received"
        case messageContent = "message_content"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(conversationId, forKey: .conversationId)
        try container.encodeIfPresent(messageTo, forKey: .messageTo)
        try container.encodeIfPresent(messageFrom, forKey: .messageFrom)
        try container.encodeIfPresent(timeSent, forKey: .timeSent)
        try container.encodeIfPresent(timeReceived, forKey: .timeReceived)
        try container.encodeIfPresent(messageContent, forKey: .messageContent)
        try container.encodeIfPresent(status, forKey: .status)
    }
}


extension SecureMessage: Identifiable {}

extension SecureMessage: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
