//
// SecureMessageConversationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing all messages in a conversation */
public struct SecureMessageConversationResponse: Sendable, Codable, Hashable {

    public var messages: [SecureMessage]?

    public init(messages: [SecureMessage]? = nil) {
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messages, forKey: .messages)
    }
}

