//
// SecureMessageCommonFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SecureMessageCommonFields: Sendable, Codable, Hashable {

    /** Content of the message */
    public var messageContent: String
    /** ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context. */
    public var conversationId: String

    public init(messageContent: String, conversationId: String) {
        self.messageContent = messageContent
        self.conversationId = conversationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageContent = "message_content"
        case conversationId = "conversation_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messageContent, forKey: .messageContent)
        try container.encode(conversationId, forKey: .conversationId)
    }
}

