//
// SecureMessageReceiveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to receive a secure message */
public struct SecureMessageReceiveRequest: Sendable, Codable, Hashable {

    /** Content of the message */
    public var messageContent: String
    /** ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context. */
    public var conversationId: String
    /** Sender user ID */
    public var messageFrom: String

    public init(messageContent: String, conversationId: String, messageFrom: String) {
        self.messageContent = messageContent
        self.conversationId = conversationId
        self.messageFrom = messageFrom
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageContent = "message_content"
        case conversationId = "conversation_id"
        case messageFrom = "message_from"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messageContent, forKey: .messageContent)
        try container.encode(conversationId, forKey: .conversationId)
        try container.encode(messageFrom, forKey: .messageFrom)
    }
}

