//
// TimelineSingleItemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing a single timeline item, which can be a referral, secure message, or calendar event */
public struct TimelineSingleItemResponse: Sendable, Codable, Hashable {

    public var success: Int?
    public var timelineItem: TimelineSingleItemResponseTimelineItem?

    public init(success: Int? = nil, timelineItem: TimelineSingleItemResponseTimelineItem? = nil) {
        self.success = success
        self.timelineItem = timelineItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case timelineItem = "timeline_item"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(timelineItem, forKey: .timelineItem)
    }
}

