//
// TimelineItemCalendarEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single timeline item representing a calendar event */
public struct TimelineItemCalendarEvent: Sendable, Codable, Hashable {

    /** Type of feature block this timeline item belongs to */
    public var featureBlock: String?
    /** ID of the feature block */
    public var featureBlockId: Int?
    public var instance: String?
    public var source: String?
    public var createdTimestamp: String?
    public var updatedTimestamp: String?
    public var externalUid: String?
    public var title: String?
    public var description: String?
    public var startTimestamp: String?
    public var endTimestamp: String?
    public var organiser: String?
    public var attendee: String?
    public var status: String?
    public var location: String?
    public var type: String?
    public var tags: String?
    public var trigger: String?
    public var action: String?
    public var reminderDescription: String?
    public var durationString: String?
    public var durationOfEvent: Float?

    public init(featureBlock: String? = nil, featureBlockId: Int? = nil, instance: String? = nil, source: String? = nil, createdTimestamp: String? = nil, updatedTimestamp: String? = nil, externalUid: String? = nil, title: String? = nil, description: String? = nil, startTimestamp: String? = nil, endTimestamp: String? = nil, organiser: String? = nil, attendee: String? = nil, status: String? = nil, location: String? = nil, type: String? = nil, tags: String? = nil, trigger: String? = nil, action: String? = nil, reminderDescription: String? = nil, durationString: String? = nil, durationOfEvent: Float? = nil) {
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.instance = instance
        self.source = source
        self.createdTimestamp = createdTimestamp
        self.updatedTimestamp = updatedTimestamp
        self.externalUid = externalUid
        self.title = title
        self.description = description
        self.startTimestamp = startTimestamp
        self.endTimestamp = endTimestamp
        self.organiser = organiser
        self.attendee = attendee
        self.status = status
        self.location = location
        self.type = type
        self.tags = tags
        self.trigger = trigger
        self.action = action
        self.reminderDescription = reminderDescription
        self.durationString = durationString
        self.durationOfEvent = durationOfEvent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case instance
        case source
        case createdTimestamp = "created_timestamp"
        case updatedTimestamp = "updated_timestamp"
        case externalUid = "external_uid"
        case title
        case description
        case startTimestamp = "start_timestamp"
        case endTimestamp = "end_timestamp"
        case organiser
        case attendee
        case status
        case location
        case type
        case tags
        case trigger
        case action
        case reminderDescription = "reminder_description"
        case durationString = "duration_string"
        case durationOfEvent = "duration_of_event"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(instance, forKey: .instance)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(updatedTimestamp, forKey: .updatedTimestamp)
        try container.encodeIfPresent(externalUid, forKey: .externalUid)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(endTimestamp, forKey: .endTimestamp)
        try container.encodeIfPresent(organiser, forKey: .organiser)
        try container.encodeIfPresent(attendee, forKey: .attendee)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(trigger, forKey: .trigger)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(reminderDescription, forKey: .reminderDescription)
        try container.encodeIfPresent(durationString, forKey: .durationString)
        try container.encodeIfPresent(durationOfEvent, forKey: .durationOfEvent)
    }
}

