//
// TimelineResponseTimelineInnerOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Referral item */
public struct TimelineResponseTimelineInnerOneOf: Sendable, Codable, Hashable {

    public var id: Int?
    public var featureBlock: String?
    public var featureBlockId: String?
    public var startTimestamp: String?
    public var itemTimestamp: Int?
    public var serviceDescription: String?
    public var serviceName: String?
    public var contactName: String?
    public var contactTitle: String?
    public var memo: String?
    public var status: String?

    public init(id: Int? = nil, featureBlock: String? = nil, featureBlockId: String? = nil, startTimestamp: String? = nil, itemTimestamp: Int? = nil, serviceDescription: String? = nil, serviceName: String? = nil, contactName: String? = nil, contactTitle: String? = nil, memo: String? = nil, status: String? = nil) {
        self.id = id
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.startTimestamp = startTimestamp
        self.itemTimestamp = itemTimestamp
        self.serviceDescription = serviceDescription
        self.serviceName = serviceName
        self.contactName = contactName
        self.contactTitle = contactTitle
        self.memo = memo
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case startTimestamp = "start_timestamp"
        case itemTimestamp = "item_timestamp"
        case serviceDescription = "service_description"
        case serviceName = "service_name"
        case contactName = "contact_name"
        case contactTitle = "contact_title"
        case memo
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(itemTimestamp, forKey: .itemTimestamp)
        try container.encodeIfPresent(serviceDescription, forKey: .serviceDescription)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(contactName, forKey: .contactName)
        try container.encodeIfPresent(contactTitle, forKey: .contactTitle)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(status, forKey: .status)
    }
}


extension TimelineResponseTimelineInnerOneOf: Identifiable {}
