//
// TimelineResponseTimelineInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TimelineResponseTimelineInner: Sendable, Codable, Hashable {
    case typeTimelineResponseTimelineInnerOneOf(TimelineResponseTimelineInnerOneOf)
    case typeTimelineResponseTimelineInnerOneOf1(TimelineResponseTimelineInnerOneOf1)
    case typeTimelineResponseTimelineInnerOneOf2(TimelineResponseTimelineInnerOneOf2)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimelineResponseTimelineInnerOneOf(let value):
            try container.encode(value)
        case .typeTimelineResponseTimelineInnerOneOf1(let value):
            try container.encode(value)
        case .typeTimelineResponseTimelineInnerOneOf2(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimelineResponseTimelineInnerOneOf.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineResponseTimelineInnerOneOf(value)
        } else if let value = try? container.decode(TimelineResponseTimelineInnerOneOf1.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineResponseTimelineInnerOneOf1(value)
        } else if let value = try? container.decode(TimelineResponseTimelineInnerOneOf2.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineResponseTimelineInnerOneOf2(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of TimelineResponseTimelineInner"))
        }
    }
}


extension TimelineResponseTimelineInner: Identifiable {}
