//
// TimelineItemSecureMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single timeline item representing a secure message */
public struct TimelineItemSecureMessage: Sendable, Codable, Hashable {

    /** Type of feature block this timeline item belongs to */
    public var featureBlock: String?
    /** ID of the feature block */
    public var featureBlockId: Int?
    /** Formatted start timestamp for display */
    public var startTimestamp: String?
    /** Raw timestamp of the timeline item */
    public var itemTimestamp: Int64?
    public var createdTimestamp: Int64?
    public var updatedTimestamp: Int64?
    /** Conversation identifier */
    public var conversationId: String?
    /** Timestamp when message was sent */
    public var timeSent: String?
    /** Timestamp when message was received */
    public var timeReceived: String?
    /** Sender of the message (present on received messages) */
    public var messageFrom: String?
    /** Recipient of the message (present on sent messages) */
    public var messageTo: String?
    /** Content of the message */
    public var messageContent: String?

    public init(featureBlock: String? = nil, featureBlockId: Int? = nil, startTimestamp: String? = nil, itemTimestamp: Int64? = nil, createdTimestamp: Int64? = nil, updatedTimestamp: Int64? = nil, conversationId: String? = nil, timeSent: String? = nil, timeReceived: String? = nil, messageFrom: String? = nil, messageTo: String? = nil, messageContent: String? = nil) {
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.startTimestamp = startTimestamp
        self.itemTimestamp = itemTimestamp
        self.createdTimestamp = createdTimestamp
        self.updatedTimestamp = updatedTimestamp
        self.conversationId = conversationId
        self.timeSent = timeSent
        self.timeReceived = timeReceived
        self.messageFrom = messageFrom
        self.messageTo = messageTo
        self.messageContent = messageContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case startTimestamp = "start_timestamp"
        case itemTimestamp = "item_timestamp"
        case createdTimestamp = "created_timestamp"
        case updatedTimestamp = "updated_timestamp"
        case conversationId = "conversation_id"
        case timeSent = "time_sent"
        case timeReceived = "time_received"
        case messageFrom = "message_from"
        case messageTo = "message_to"
        case messageContent = "message_content"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(itemTimestamp, forKey: .itemTimestamp)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(updatedTimestamp, forKey: .updatedTimestamp)
        try container.encodeIfPresent(conversationId, forKey: .conversationId)
        try container.encodeIfPresent(timeSent, forKey: .timeSent)
        try container.encodeIfPresent(timeReceived, forKey: .timeReceived)
        try container.encodeIfPresent(messageFrom, forKey: .messageFrom)
        try container.encodeIfPresent(messageTo, forKey: .messageTo)
        try container.encodeIfPresent(messageContent, forKey: .messageContent)
    }
}

