//
// TimelineSingleItemResponseTimelineItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The timeline item, which can be one of multiple types, returned as an object */
public enum TimelineSingleItemResponseTimelineItem: Sendable, Codable, Hashable {
    case typeTimelineItemCalendarEvent(TimelineItemCalendarEvent)
    case typeTimelineItemReferral(TimelineItemReferral)
    case typeTimelineItemSecureMessage(TimelineItemSecureMessage)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimelineItemCalendarEvent(let value):
            try container.encode(value)
        case .typeTimelineItemReferral(let value):
            try container.encode(value)
        case .typeTimelineItemSecureMessage(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimelineItemCalendarEvent.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineItemCalendarEvent(value)
        } else if let value = try? container.decode(TimelineItemReferral.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineItemReferral(value)
        } else if let value = try? container.decode(TimelineItemSecureMessage.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTimelineItemSecureMessage(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of TimelineSingleItemResponseTimelineItem"))
        }
    }
}

