//
// TimelineResponseTimelineInnerOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Secure message item */
public struct TimelineResponseTimelineInnerOneOf1: Sendable, Codable, Hashable {

    public var id: Int?
    public var featureBlock: String?
    public var featureBlockId: String?
    public var startTimestamp: String?
    public var itemTimestamp: Int?
    public var createdTimestamp: Int?
    public var messageFrom: String?
    public var messageTo: String?
    public var messageContent: String?

    public init(id: Int? = nil, featureBlock: String? = nil, featureBlockId: String? = nil, startTimestamp: String? = nil, itemTimestamp: Int? = nil, createdTimestamp: Int? = nil, messageFrom: String? = nil, messageTo: String? = nil, messageContent: String? = nil) {
        self.id = id
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.startTimestamp = startTimestamp
        self.itemTimestamp = itemTimestamp
        self.createdTimestamp = createdTimestamp
        self.messageFrom = messageFrom
        self.messageTo = messageTo
        self.messageContent = messageContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case startTimestamp = "start_timestamp"
        case itemTimestamp = "item_timestamp"
        case createdTimestamp = "created_timestamp"
        case messageFrom = "message_from"
        case messageTo = "message_to"
        case messageContent = "message_content"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(itemTimestamp, forKey: .itemTimestamp)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(messageFrom, forKey: .messageFrom)
        try container.encodeIfPresent(messageTo, forKey: .messageTo)
        try container.encodeIfPresent(messageContent, forKey: .messageContent)
    }
}


extension TimelineResponseTimelineInnerOneOf1: Identifiable {}
