//
// TimelineResponseTimelineInnerOneOf2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Calendar event item */
public struct TimelineResponseTimelineInnerOneOf2: Sendable, Codable, Hashable {

    public var id: Int?
    public var featureBlock: String?
    public var featureBlockId: String?
    public var startTimestamp: String?
    public var itemTimestamp: Int?
    public var endTimestamp: String?
    public var title: String?
    public var location: String?
    public var organiser: String?
    public var description: String?
    public var status: String?
    public var durationString: String?
    public var durationOfEvent: Double?

    public init(id: Int? = nil, featureBlock: String? = nil, featureBlockId: String? = nil, startTimestamp: String? = nil, itemTimestamp: Int? = nil, endTimestamp: String? = nil, title: String? = nil, location: String? = nil, organiser: String? = nil, description: String? = nil, status: String? = nil, durationString: String? = nil, durationOfEvent: Double? = nil) {
        self.id = id
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.startTimestamp = startTimestamp
        self.itemTimestamp = itemTimestamp
        self.endTimestamp = endTimestamp
        self.title = title
        self.location = location
        self.organiser = organiser
        self.description = description
        self.status = status
        self.durationString = durationString
        self.durationOfEvent = durationOfEvent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case startTimestamp = "start_timestamp"
        case itemTimestamp = "item_timestamp"
        case endTimestamp = "end_timestamp"
        case title
        case location
        case organiser
        case description
        case status
        case durationString = "duration_string"
        case durationOfEvent = "duration_of_event"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(itemTimestamp, forKey: .itemTimestamp)
        try container.encodeIfPresent(endTimestamp, forKey: .endTimestamp)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(organiser, forKey: .organiser)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(durationString, forKey: .durationString)
        try container.encodeIfPresent(durationOfEvent, forKey: .durationOfEvent)
    }
}


extension TimelineResponseTimelineInnerOneOf2: Identifiable {}
