//
// TimelineItemReferral.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single timeline item representing a referral */
public struct TimelineItemReferral: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case referred = "Referred"
        case inProgress = "In Progress"
        case accepted = "Accepted"
        case rejected = "Rejected"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Type of feature block this timeline item belongs to */
    public var featureBlock: String?
    /** ID of the feature block record i.e. the referral id */
    public var featureBlockId: Int?
    public var instance: String?
    /** The context within which this record was created i.e. the specific connection */
    public var source: String?
    public var createdTimestamp: Int64?
    public var updatedTimestamp: Int64?
    /** The id of the service that the referral relates to */
    public var serviceId: Int?
    public var serviceName: String?
    public var serviceDescription: String?
    public var serviceUrl: String?
    public var serviceEmail: String?
    public var contactName: String?
    public var contactTitle: String?
    public var contactNumber: String?
    public var referrerName: String?
    public var status: Status?
    public var externalId: String?
    public var startTime: Int64?
    public var endTime: Int64?
    public var isProcessed: Bool?
    public var completeTime: Int?
    public var memo: String?
    public var duration: String?
    public var referreeBackground: String?
    public var referreeRequirements: String?
    /** Availability of the referree in AM/PM slots */
    public var referreeAvailability: JSONValue?
    public var type: String?
    public var startTimestamp: String?

    public init(featureBlock: String? = nil, featureBlockId: Int? = nil, instance: String? = nil, source: String? = nil, createdTimestamp: Int64? = nil, updatedTimestamp: Int64? = nil, serviceId: Int? = nil, serviceName: String? = nil, serviceDescription: String? = nil, serviceUrl: String? = nil, serviceEmail: String? = nil, contactName: String? = nil, contactTitle: String? = nil, contactNumber: String? = nil, referrerName: String? = nil, status: Status? = nil, externalId: String? = nil, startTime: Int64? = nil, endTime: Int64? = nil, isProcessed: Bool? = nil, completeTime: Int? = nil, memo: String? = nil, duration: String? = nil, referreeBackground: String? = nil, referreeRequirements: String? = nil, referreeAvailability: JSONValue? = nil, type: String? = nil, startTimestamp: String? = nil) {
        self.featureBlock = featureBlock
        self.featureBlockId = featureBlockId
        self.instance = instance
        self.source = source
        self.createdTimestamp = createdTimestamp
        self.updatedTimestamp = updatedTimestamp
        self.serviceId = serviceId
        self.serviceName = serviceName
        self.serviceDescription = serviceDescription
        self.serviceUrl = serviceUrl
        self.serviceEmail = serviceEmail
        self.contactName = contactName
        self.contactTitle = contactTitle
        self.contactNumber = contactNumber
        self.referrerName = referrerName
        self.status = status
        self.externalId = externalId
        self.startTime = startTime
        self.endTime = endTime
        self.isProcessed = isProcessed
        self.completeTime = completeTime
        self.memo = memo
        self.duration = duration
        self.referreeBackground = referreeBackground
        self.referreeRequirements = referreeRequirements
        self.referreeAvailability = referreeAvailability
        self.type = type
        self.startTimestamp = startTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featureBlock = "feature_block"
        case featureBlockId = "feature_block_id"
        case instance
        case source
        case createdTimestamp = "created_timestamp"
        case updatedTimestamp = "updated_timestamp"
        case serviceId = "service_id"
        case serviceName = "service_name"
        case serviceDescription = "service_description"
        case serviceUrl = "service_url"
        case serviceEmail = "service_email"
        case contactName = "contact_name"
        case contactTitle = "contact_title"
        case contactNumber = "contact_number"
        case referrerName = "referrer_name"
        case status
        case externalId = "external_id"
        case startTime = "start_time"
        case endTime = "end_time"
        case isProcessed = "is_processed"
        case completeTime = "complete_time"
        case memo
        case duration
        case referreeBackground = "referree_background"
        case referreeRequirements = "referree_requirements"
        case referreeAvailability = "referree_availability"
        case type
        case startTimestamp = "start_timestamp"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(featureBlock, forKey: .featureBlock)
        try container.encodeIfPresent(featureBlockId, forKey: .featureBlockId)
        try container.encodeIfPresent(instance, forKey: .instance)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(createdTimestamp, forKey: .createdTimestamp)
        try container.encodeIfPresent(updatedTimestamp, forKey: .updatedTimestamp)
        try container.encodeIfPresent(serviceId, forKey: .serviceId)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(serviceDescription, forKey: .serviceDescription)
        try container.encodeIfPresent(serviceUrl, forKey: .serviceUrl)
        try container.encodeIfPresent(serviceEmail, forKey: .serviceEmail)
        try container.encodeIfPresent(contactName, forKey: .contactName)
        try container.encodeIfPresent(contactTitle, forKey: .contactTitle)
        try container.encodeIfPresent(contactNumber, forKey: .contactNumber)
        try container.encodeIfPresent(referrerName, forKey: .referrerName)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
        try container.encodeIfPresent(isProcessed, forKey: .isProcessed)
        try container.encodeIfPresent(completeTime, forKey: .completeTime)
        try container.encodeIfPresent(memo, forKey: .memo)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(referreeBackground, forKey: .referreeBackground)
        try container.encodeIfPresent(referreeRequirements, forKey: .referreeRequirements)
        try container.encodeIfPresent(referreeAvailability, forKey: .referreeAvailability)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
    }
}


extension TimelineItemReferral: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
