//
// TimelineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing a mixed timeline of calendar events, referrals, and secure messages */
public struct TimelineResponse: Sendable, Codable, Hashable {

    public var success: Int?
    /** Array of timeline items, which can be calendar events, referrals, or secure messages */
    public var timeline: [TimelineResponseTimelineInner]?

    public init(success: Int? = nil, timeline: [TimelineResponseTimelineInner]? = nil) {
        self.success = success
        self.timeline = timeline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case timeline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(timeline, forKey: .timeline)
    }
}

