//
// UpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateResponse: Sendable, Codable, Hashable {

    /** Indicates success */
    public var success: Int?

    public init(success: Int? = nil) {
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
    }
}

