//
// CalendarAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CalendarAPI {

    /**
     Supports deleting a calendar-event.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventDeleteRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeleteResponse
     */
    open class func deleteCalendarEvent(connectionToken: String, uid: String, conId: String, calendarEventDeleteRequestBody: CalendarEventDeleteRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeleteResponse {
        return try await deleteCalendarEventWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, calendarEventDeleteRequestBody: calendarEventDeleteRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports deleting a calendar-event.
     - DELETE /calendar/delete-event
     - Deletes an event in the user's calendar.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventDeleteRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeleteResponse> 
     */
    open class func deleteCalendarEventWithRequestBuilder(connectionToken: String, uid: String, conId: String, calendarEventDeleteRequestBody: CalendarEventDeleteRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<DeleteResponse> {
        let localVariablePath = "/calendar/delete-event"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: calendarEventDeleteRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Retrieve appointments for a given context
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter context: (query) The context this belongs to 
     - parameter contextId: (query) The specific ID of the context record 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetAppointmentsResponse
     */
    open class func getCalendarAppointments(connectionToken: String, uid: String, conId: String, context: String, contextId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetAppointmentsResponse {
        return try await getCalendarAppointmentsWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, context: context, contextId: contextId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve appointments for a given context
     - GET /calendar/get-appointments
     - Returns a list of appointments filtered by context and context_id.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter context: (query) The context this belongs to 
     - parameter contextId: (query) The specific ID of the context record 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetAppointmentsResponse> 
     */
    open class func getCalendarAppointmentsWithRequestBuilder(connectionToken: String, uid: String, conId: String, context: String, contextId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetAppointmentsResponse> {
        let localVariablePath = "/calendar/get-appointments"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "context": (wrappedValue: context.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "context_id": (wrappedValue: contextId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAppointmentsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Retrieve calendar events
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetEventsResponse
     */
    open class func getCalendarEvents(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetEventsResponse {
        return try await getCalendarEventsWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve calendar events
     - GET /calendar/get-events
     - Returns a list of calendar events.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetEventsResponse> 
     */
    open class func getCalendarEventsWithRequestBuilder(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetEventsResponse> {
        let localVariablePath = "/calendar/get-events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetEventsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports adding a calendar-appointment.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarAppointmentCreateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateResponse
     */
    open class func postCalendarAppointment(connectionToken: String, uid: String, conId: String, calendarAppointmentCreateRequestBody: CalendarAppointmentCreateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CreateResponse {
        return try await postCalendarAppointmentWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, calendarAppointmentCreateRequestBody: calendarAppointmentCreateRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports adding a calendar-appointment.
     - POST /calendar/add-appointment
     - Creates a new appointment in the user's calendar. An appointment must be made within a specified context e.g. a 'Referral'
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarAppointmentCreateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateResponse> 
     */
    open class func postCalendarAppointmentWithRequestBuilder(connectionToken: String, uid: String, conId: String, calendarAppointmentCreateRequestBody: CalendarAppointmentCreateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CreateResponse> {
        let localVariablePath = "/calendar/add-appointment"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: calendarAppointmentCreateRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports adding a calendar-event.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventCreateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateResponse
     */
    open class func postCalendarEvent(connectionToken: String, uid: String, conId: String, calendarEventCreateRequestBody: CalendarEventCreateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CreateResponse {
        return try await postCalendarEventWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, calendarEventCreateRequestBody: calendarEventCreateRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports adding a calendar-event.
     - POST /calendar/add-event
     - Creates a new event in the user's calendar.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventCreateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateResponse> 
     */
    open class func postCalendarEventWithRequestBuilder(connectionToken: String, uid: String, conId: String, calendarEventCreateRequestBody: CalendarEventCreateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CreateResponse> {
        let localVariablePath = "/calendar/add-event"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: calendarEventCreateRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports updating a calendar-event.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventUpdateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UpdateResponse
     */
    open class func putCalendarEvent(connectionToken: String, uid: String, conId: String, calendarEventUpdateRequestBody: CalendarEventUpdateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> UpdateResponse {
        return try await putCalendarEventWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, calendarEventUpdateRequestBody: calendarEventUpdateRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports updating a calendar-event.
     - PUT /calendar/update-event
     - Updates an event in the user's calendar. For example, updating the 'status' from 'INVITED' to 'CONFIRMED' when a user accepts the invitation to an appointment.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter calendarEventUpdateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UpdateResponse> 
     */
    open class func putCalendarEventWithRequestBuilder(connectionToken: String, uid: String, conId: String, calendarEventUpdateRequestBody: CalendarEventUpdateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<UpdateResponse> {
        let localVariablePath = "/calendar/update-event"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: calendarEventUpdateRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
