//
// ReferralsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ReferralsAPI {

    /**
     Retrieve rall referrals for a given member.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReferralListResponse
     */
    open class func getAllReferrals(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ReferralListResponse {
        return try await getAllReferralsWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve rall referrals for a given member.
     - GET /referrals/read-all
     - Returns a list of referrals.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReferralListResponse> 
     */
    open class func getAllReferralsWithRequestBuilder(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ReferralListResponse> {
        let localVariablePath = "/referrals/read-all"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReferralListResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Retrieve a single referral by id for a given member.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter id: (query) The record id requested. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReferralSingleResponse
     */
    open class func getSingleReferral(connectionToken: String, uid: String, conId: String, id: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ReferralSingleResponse {
        return try await getSingleReferralWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve a single referral by id for a given member.
     - GET /referrals/read-single
     - Returns the requested referral.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter id: (query) The record id requested. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReferralSingleResponse> 
     */
    open class func getSingleReferralWithRequestBuilder(connectionToken: String, uid: String, conId: String, id: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ReferralSingleResponse> {
        let localVariablePath = "/referrals/read-single"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "id": (wrappedValue: id.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReferralSingleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports self-referral.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter selfReferralRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateResponse
     */
    open class func postSelfReferral(connectionToken: String, uid: String, conId: String, selfReferralRequestBody: SelfReferralRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CreateResponse {
        return try await postSelfReferralWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, selfReferralRequestBody: selfReferralRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports self-referral.
     - POST /referrals/self-refer
     - Creates a new referral of type 'Self Referred' in the member's PDS.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter selfReferralRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateResponse> 
     */
    open class func postSelfReferralWithRequestBuilder(connectionToken: String, uid: String, conId: String, selfReferralRequestBody: SelfReferralRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CreateResponse> {
        let localVariablePath = "/referrals/self-refer"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: selfReferralRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports updating the status of a referral.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter referralStatusUpdateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UpdateResponse
     */
    open class func updateReferralStatus(connectionToken: String, uid: String, conId: String, referralStatusUpdateRequestBody: ReferralStatusUpdateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> UpdateResponse {
        return try await updateReferralStatusWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, referralStatusUpdateRequestBody: referralStatusUpdateRequestBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports updating the status of a referral.
     - PUT /referrals/update-status
     - Updates the status of a member's referral specified by id. For example, having been referred to a service, the status is set by default to 'Referred' and this route enables it to be updated to 'Accepted' or 'Rejected'
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter referralStatusUpdateRequestBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UpdateResponse> 
     */
    open class func updateReferralStatusWithRequestBuilder(connectionToken: String, uid: String, conId: String, referralStatusUpdateRequestBody: ReferralStatusUpdateRequestBody? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<UpdateResponse> {
        let localVariablePath = "/referrals/update-status"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: referralStatusUpdateRequestBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
