//
// SecureMessagesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SecureMessagesAPI {

    /**
     Retrieve all secure messages for a given conversation.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter conversationId: (query) The specific ID of the conversation that groups messages together 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SecureMessageConversationResponse
     */
    open class func getSecureMessageConversation(connectionToken: String, uid: String, conId: String, conversationId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> SecureMessageConversationResponse {
        return try await getSecureMessageConversationWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, conversationId: conversationId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve all secure messages for a given conversation.
     - GET /secure-messages/conversation
     - Returns a list of secure messages that form part of a conversation.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter conversationId: (query) The specific ID of the conversation that groups messages together 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SecureMessageConversationResponse> 
     */
    open class func getSecureMessageConversationWithRequestBuilder(connectionToken: String, uid: String, conId: String, conversationId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<SecureMessageConversationResponse> {
        let localVariablePath = "/secure-messages/conversation"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "conversation_id": (wrappedValue: conversationId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SecureMessageConversationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports sending a message to the member's PDS.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter secureMessageReceiveRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateResponse
     */
    open class func postSecureMessageReceive(connectionToken: String, uid: String, conId: String, secureMessageReceiveRequest: SecureMessageReceiveRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CreateResponse {
        return try await postSecureMessageReceiveWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, secureMessageReceiveRequest: secureMessageReceiveRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports sending a message to the member's PDS.
     - POST /secure-messages/receive
     - Creates a new received message in the member's PDS.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter secureMessageReceiveRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateResponse> 
     */
    open class func postSecureMessageReceiveWithRequestBuilder(connectionToken: String, uid: String, conId: String, secureMessageReceiveRequest: SecureMessageReceiveRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CreateResponse> {
        let localVariablePath = "/secure-messages/receive"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: secureMessageReceiveRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Supports sending a message from the member's PDS.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter secureMessageSendRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateResponse
     */
    open class func postSecureMessageSend(connectionToken: String, uid: String, conId: String, secureMessageSendRequest: SecureMessageSendRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CreateResponse {
        return try await postSecureMessageSendWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, secureMessageSendRequest: secureMessageSendRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Supports sending a message from the member's PDS.
     - POST /secure-messages/send
     - Creates a new sent message in the member's PDS.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter secureMessageSendRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateResponse> 
     */
    open class func postSecureMessageSendWithRequestBuilder(connectionToken: String, uid: String, conId: String, secureMessageSendRequest: SecureMessageSendRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<CreateResponse> {
        let localVariablePath = "/secure-messages/send"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: secureMessageSendRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
