//
// TimelineAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TimelineAPI {

    /**
     Retrieve list of timeline items.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TimelineResponse
     */
    open class func getTimeline(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> TimelineResponse {
        return try await getTimelineWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve list of timeline items.
     - GET /timeline
     - Returns a list of timeline items which includes: referrals, calendar events and secure messages.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TimelineResponse> 
     */
    open class func getTimelineWithRequestBuilder(connectionToken: String, uid: String, conId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<TimelineResponse> {
        let localVariablePath = "/timeline"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TimelineResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter featureBlock
     */
    public enum FeatureBlock_getTimelineItem: String, Sendable, CaseIterable {
        case referrals = "referrals"
        case secureMessages = "secure_messages"
        case calendar = "calendar"
    }

    /**
     Retrieve a single timeline item.
     
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter featureBlock: (query) The feature block the teimline item belongs to 
     - parameter featureBlockId: (query) The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TimelineSingleItemResponse
     */
    open class func getTimelineItem(connectionToken: String, uid: String, conId: String, featureBlock: FeatureBlock_getTimelineItem, featureBlockId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> TimelineSingleItemResponse {
        return try await getTimelineItemWithRequestBuilder(connectionToken: connectionToken, uid: uid, conId: conId, featureBlock: featureBlock, featureBlockId: featureBlockId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieve a single timeline item.
     - GET /timeline/single-item
     - Returns a single timeline item based on feature block and feature block id requested e.g. a 'referral' with id 123.
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter connectionToken: (header) Member&#39;s Connection Key 
     - parameter uid: (query) The unique ID of a mydex member 
     - parameter conId: (query) The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID. 
     - parameter featureBlock: (query) The feature block the teimline item belongs to 
     - parameter featureBlockId: (query) The specific ID of the record within the specified feature block e.g. if &#39;referrals&#39; is the feature block, then this should be a specific referral id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TimelineSingleItemResponse> 
     */
    open class func getTimelineItemWithRequestBuilder(connectionToken: String, uid: String, conId: String, featureBlock: FeatureBlock_getTimelineItem, featureBlockId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<TimelineSingleItemResponse> {
        let localVariablePath = "/timeline/single-item"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "uid": (wrappedValue: uid.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "con_id": (wrappedValue: conId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "feature_block": (wrappedValue: featureBlock.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "feature_block_id": (wrappedValue: featureBlockId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Connection-Token": connectionToken.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TimelineSingleItemResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
